### PR TITLE
Fix email validation to abide by RFC5322

### LINKED ISSUE #121: [PE-D][Tester B] Functionality Bug with regards to invalid email inputs
Invalid email addresses is not handled properly. Incases where users do not input the email correctly in the command, ending with numerous .com.com.com it will still be accepted. Understand that there may be cases where users need to key in .com.sg but may lead to other invalid emails.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jamieeeleow/ped#1

### PR DESCRIPTION
**Pull request by glyfy**
Resolves #121 
Not perfect and does not check for repeated domain (e.g. .com.com) but is a more comprehensive version (for example does not allow glen@mail..com and glen@-mail.com)

### CODE REVIEW

File: src/test/java/expresslibrary/model/person/EmailTest.java [hunk 1]
```diff
@@ -42,8 +42,6 @@ public void isValidEmail() {
         assertFalse(Email.isValidEmail("peterjack@example.com ")); // trailing space
         assertFalse(Email.isValidEmail("peterjack@@example.com")); // double '@' symbol
         assertFalse(Email.isValidEmail("peter@jack@example.com")); // '@' symbol in local part
-        assertFalse(Email.isValidEmail("-peterjack@example.com")); // local part starts with a hyphen
-        assertFalse(Email.isValidEmail("peterjack-@example.com")); // local part ends with a hyphen
```
Comment (Jarrett0203) [inline src/test/java/expresslibrary/model/person/EmailTest.java:46]: Probably can change this to assertTrue instead of removing it

File: src/test/java/expresslibrary/model/person/EmailTest.java [hunk 2]
```diff
@@ -57,9 +55,6 @@ public void isValidEmail() {
         assertTrue(Email.isValidEmail("PeterJack.1190@example.com")); // period in local part
         assertTrue(Email.isValidEmail("PeterJack+1190@example.com")); // '+' symbol in local part
         assertTrue(Email.isValidEmail("PeterJack-1190@example.com")); // hyphen in local part
-        assertTrue(Email.isValidEmail("a@bc")); // minimal
-        assertTrue(Email.isValidEmail("test@localhost")); // alphabets only
-        assertTrue(Email.isValidEmail("123@145")); // numeric local part and domain name
```
Comment (Jarrett0203) [inline src/test/java/expresslibrary/model/person/EmailTest.java:62]: Can also change this to assertFalse

File: src/main/java/expresslibrary/model/person/Email.java [hunk 3]
```diff
@@ -9,27 +9,21 @@
...
             + "that can be used and the maximum length of each label.\n"
             + "The overall length of the email address cannot exceed 256 characters.";
-    // alphanumeric and special characters
-    private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
-    private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE + "([" + SPECIAL_CHARACTERS + "]"
-            + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    private static final String DOMAIN_PART_REGEX = ALPHANUMERIC_NO_UNDERSCORE
-            + "(-" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    public static final String VALIDATION_REGEX = "^(?=.{1,256}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+(\\.[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]+)*@([a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$";
+    public static final String VALIDATION_REGEX = "^(?=.{1,256}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+/=?^_`{|}~-]"
```
Comment (Jarrett0203) [inline src/main/java/expresslibrary/model/person/Email.java:25]: Probably also want to reference where you got this regex from according to the tp reuse policy. 
[https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/admin.html#policy-on-reuse](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/admin.html#policy-on-reuse)

**Review by Jarrett0203 — CHANGES_REQUESTED** [review]
Might also want to update the UG on the new email constraints.

**Review by Jarrett0203 — APPROVED** [review]
LGTM
