### PR TITLE
Fix Edit Commands

### LINKED ISSUE #103: Fix EditBookCommand bug
After editing the title of a book which is borrowed by someone, the book becomes not borrowed and the book title in the Person's borrowed books list doesn't reflect the change.

### PR DESCRIPTION
**Pull request by Jarrett0203**
Resolves #103, #104.

Ignore the UG/DG changes was just testing the website on my local repo
(commits are duplicates of another PR to fix UG/DG so should be fine to merge this)

### CODE REVIEW

File: src/main/java/expresslibrary/commons/core/Messages.java [hunk 1]
```diff
@@ -10,6 +10,10 @@ public class Messages {
     public static final String MESSAGE_INVALID_BOOK_DISPLAYED_INDEX = "The book index provided is invalid";
     public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid";
     public static final String MESSAGE_BOOK_BORROWED = "The book is already borrowed";
+    public static final String MESSAGE_BOOK_BORROWED_NOT_FOUND =
+        "The person has borrowed a book but is not found in book list";
```
Comment (sanjevi13) [inline src/main/java/expresslibrary/commons/core/Messages.java:14]:
```suggestion
        "The book is not found in the book list";
```

File: src/main/java/expresslibrary/commons/core/Messages.java [hunk 2]
```diff
@@ -10,6 +10,10 @@ public class Messages {
...
+    public static final String MESSAGE_BORROWER_NOT_FOUND =
+        "The book is borrowed but the person is not found in person list";
```
Comment (sanjevi13) [inline src/main/java/expresslibrary/commons/core/Messages.java:16]:
```suggestion
        "The person is not found in the person list";
```

**Review by sanjevi13 — CHANGES_REQUESTED** [review]
Not much to change, just 2 of the strings are slightly long, can cut short.

**Review by sanjevi13 — APPROVED** [review]
LGTM
